### ISSUE TITLE
To run codes  step by step explain

### ISSUE THREAD

**Issue by Kiran18400k** [Tirth27/Skin-Cancer-Classification-using-Deep-Learning#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tirth27** [comment]
Hi @Kiran18400k, do you wanted to know how to run the code and reproduce the result on your end?

**Comment by Kiran18400k** [comment]
Yes 
Step by step

**Comment by Kiran18400k** [comment]
Make a video how code run

**Comment by Kiran18400k** [comment]
Make  a  video who  code is runed and how the code works

**Comment by Tirth27** [comment]
Hi @Kiran18400k, 

All the detail about the different aspects of code is explained under [./README.md](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning#skin-cancer-classification-using-deep-learning).

You can find more detail about CNN in README.md under  [Cnn Architecture Design](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning/blob/main/README.md#cnn-architecture-design).

To start the training process, run the [`./Src/Model Training/main_run.py`](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning/blob/main/Src/Model%20Training/main_run.py) file. Also, you will need to create a Compute Instance on Azure for that refer to [`./Src/README.md`](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning/blob/main/Src/README.md)

I hope that helps.
