### ISSUE TITLE
Is there some publicly available app? Or a way to run it locally?

### ISSUE THREAD

**Issue by OnHai** [Tirth27/Skin-Cancer-Classification-using-Deep-Learning#5]

**Comment by Tirth27** [comment]
Hi @Adrianahwjsgsj 

All the detail about the different aspects of code is explained under [./README.md](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning#skin-cancer-classification-using-deep-learning).

You can find more detail about CNN in README.md under [Cnn Architecture Design](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning/blob/main/README.md#cnn-architecture-design).

To start the training process, run the [./Src/Model Training/main_run.py](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning/blob/main/Src/Model%20Training/main_run.py) file. Also, you will need to create a Compute Instance on Azure for that refer to [./Src/README.md](https://github.com/Tirth27/Skin-Cancer-Classification-using-Deep-Learning/blob/main/Src/README.md)

I hope that helps.
